name: delete-hf-collections-repos

on:
  workflow_dispatch:

permissions:
 contents: write
 packages: write

# Note: by default, this workflow is configured to delete "test" repos. and collections
env:
  TARGET_REPO_OWNER: mrutkows # ibm-research
  COLLECTION_CONFIG: "resources/json/latest/hf_collection_mapping_gguf.json" # TODO: create custom mapping file as needed

jobs:
  delete-collections:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump GitHub context
      env:
        GH_CONTEXT: ${{ toJson(github) }}
      run: echo "$GH_CONTEXT"

    - name: confirm-environment
      run: |
        uname -a
        echo "runner.os: ${{ runner.os }}"
        echo "runner.arch: ${{ runner.arch }}"
        echo "github.workspace: ${{ github.workspace}}"
        echo "env.TARGET_REPO_OWNER: ${{env.TARGET_REPO_OWNER}}"
        echo "env.COLLECTION_CONFIG: ${{env.COLLECTION_CONFIG}}"

    # Note: at the current time, we cannot use Python versions > 3.11 due to HF and langchain deps.
    # Note: you can verify in a step using: run: python -c "import sys; print(sys.version)"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # primarily huggingface_hub
    - name: install-dependencies
      run: |
        python -m pip install -r ./requirements.txt
        pip list

    - name: delete-hf-collections-repos
      run: |
        python ./scripts/hf_collections_repos_delete.py ${{env.TARGET_REPO_OWNER}} ${{env.COLLECTION_CONFIG}} ${{secrets.HF_TOKEN}}
