name: ollama-publish-granite-4.0
run-name: "Ollama publish [${{github.ref_type}}: ${{github.ref_name}}]"

on:
  push:
    tags:
      - "test-ollama-4.0*"
  workflow_dispatch:

permissions:
 contents: read
 packages: read

env:
  DEBUG: true
  TRACE: false
  ENABLE_LANGUAGE_JOBS: true
  ENABLE_VISION_JOBS: false
  ENABLE_GUARDIAN_JOBS: false
  ENABLE_EMBEDDING_JOBS: false
  ENABLE_OLLAMA_PUSH: true

  # 'ibm-granite/granite-4.0-tiny-preview',
  # 'ibm-granite/granite-4.0-tiny-base-preview'

  # 'ibm-granite/granite-4.0-nano-300m',
  # 'ibm-granite/granite-4.0-nano-300m-base',
  # 'ibm-granite/granite-4.0-h-nano-300m',
  # 'ibm-granite/granite-4.0-h-nano-300m-base',
  # 'ibm-granite/granite-4.0-nano-1b',
  # 'ibm-granite/granite-4.0-nano-1b-base',
  # 'ibm-granite/granite-4.0-h-nano-1b',
  # 'ibm-granite/granite-4.0-h-nano-1b-base'

  # 'ibm-granite/granite-4.0-micro',
  # 'ibm-granite/granite-4.0-micro-base'
  # 'ibm-granite/granite-4.0-h-micro',
  # 'ibm-granite/granite-4.0-h-micro-base'
  # 'ibm-granite/granite-4.0-h-tiny',
  # 'ibm-granite/granite-4.0-h-tiny-base',
  # 'ibm-granite/granite-4.0-h-small',
  # 'ibm-granite/granite-4.0-h-small-base'
  SOURCE_INSTRUCT_REPOS: "[
    'ibm-granite/granite-4.0-micro',
    'ibm-granite/granite-4.0-h-micro',
    'ibm-granite/granite-4.0-h-tiny'
  ]"
  # 'Q2_K',
  # 'Q3_K_L', 'Q3_K_M', 'Q3_K_S',
  # 'Q4_0', 'Q4_1', 'Q4_K_M', 'Q4_K_S',
  # 'Q5_0', 'Q5_1', 'Q5_K_M', 'Q5_K_S',
  # 'Q6_K',
  # 'Q8_0'
  SOURCE_INSTRUCT_QUANTIZATIONS: "[
    'Q4_K_M', 'Q5_K_M'
  ]"
  SOURCE_GUARDIAN_REPOS: "[
    'ibm-granite/granite-guardian-3.3-8b'
  ]"
  SOURCE_GUARDIAN_QUANTIZATIONS: "[
    'Q4_K_M'
  ]"
  SOURCE_VISION_REPOS: "[
    'ibm-granite/granite-vision-3.3-2b'
  ]"
  SOURCE_VISION_QUANTIZATIONS: "[
    'Q8_0'
  ]"
  SOURCE_EMBEDDING_REPOS: "[
    'mrutkows/granite-embedding-30m-english'
  ]"
  SOURCE_EMBEDDING_QUANTIZATIONS: "[
    'Q8_0'
  ]"
  SOURCE_HF_REPO_NAME_EXT: -GGUF
  SOURCE_HF_REPO_OWNER: ibm-granite
  # SOURCE_HF_REPO_PRIVATE: false
  COLLECTION_CONFIG: "resources/json/latest/hf_collection_mapping_gguf.json"
  # orgs: ibm | mrutkows
  TARGET_OLLAMA_ORG: mrutkows

jobs:
  # ===========================================================================
  # Environment setup
  # ===========================================================================
  environment-setup:
    runs-on: ubuntu-latest
    # Note: declaration of these outputs is essential to pass to the next job
    outputs:
      debug: ${{ steps.set-vars.outputs.debug }}
      trace: ${{ steps.set-vars.outputs.trace }}
      enable_language_jobs: ${{ steps.set-vars.outputs.enable_language_jobs }}
      enable_vision_jobs: ${{ steps.set-vars.outputs.enable_vision_jobs }}
      enable_guardian_jobs: ${{ steps.set-vars.outputs.enable_guardian_jobs }}
      enable_embedding_jobs: ${{ steps.set-vars.outputs.enable_embedding_jobs }}
      hf_collection_config: ${{ steps.set-vars.outputs.hf_collection_config }}
      source_repo_private: ${{ steps.set-vars.outputs.source_repo_private }}
      source_repo_owner: ${{ steps.set-vars.outputs.source_repo_owner }}
      source_repo_name_ext: ${{ steps.set-vars.outputs.source_repo_name_ext }}
      source_instruct_repos: "${{ steps.set-vars.outputs.source_instruct_repos }}"
      source_instruct_quantizations: "${{ steps.set-vars.outputs.source_instruct_quantizations }}"
      source_vision_repos: "${{ steps.set-vars.outputs.source_vision_repos }}"
      source_vision_quantizations: "${{ steps.set-vars.outputs.source_vision_quantizations }}"
      source_guardian_repos: "${{ steps.set-vars.outputs.source_guardian_repos }}"
      source_guardian_quantizations: "${{ steps.set-vars.outputs.source_guardian_quantizations }}"
      source_embedding_repos: "${{ steps.set-vars.outputs.source_embedding_repos }}"
      source_embedding_quantizations: "${{ steps.set-vars.outputs.source_embedding_quantizations }}"
      enable_ollama_push: ${{ steps.set-vars.outputs.enable_ollama_push }}
      target_ollama_org: ${{ steps.set-vars.outputs.target_ollama_org }}
      target_ollama_llm_quants: "${{ steps.set-vars.outputs.target_ollama_llm_quants }}"
      target_ollama_guardian_quants: "${{ steps.set-vars.outputs.target_ollama_guardian_quants }}"
      target_ollama_embedding_quants: "${{ steps.set-vars.outputs.target_ollama_embedding_quants }}"
      target_ollama_vision_quants: "${{ steps.set-vars.outputs.target_ollama_vision_quants }}"
    env:
      ARRAY_SEP: "','"
      QUANT_F16: "f16"
    steps:
      - name: List all environment variables
        id: list-env-vars
        run: env | sort

      - name: Append f16 to Ollama llm quants
        id: ollama-append-llm-quants
        run: |
          echo "Appending to SOURCE_INSTRUCT_QUANTIZATIONS: '${{ fromJSON(env.SOURCE_INSTRUCT_QUANTIZATIONS) }}'"
          TEMP_ARRAY_STRING="${{ join(fromJSON(env.SOURCE_INSTRUCT_QUANTIZATIONS), env.ARRAY_SEP) }}"
          echo "TEMP_ARRAY_STRING=$TEMP_ARRAY_STRING"
          TARGET_OLLAMA_LLM_QUANTS="['${TEMP_ARRAY_STRING}${{env.ARRAY_SEP}}${{env.QUANT_F16}}']"
          echo "TARGET_OLLAMA_LLM_QUANTS=$TARGET_OLLAMA_LLM_QUANTS" >> $GITHUB_ENV

      - name: Append f16 to Ollama guardian quants
        id: ollama-append-guardian-quants
        run: |
          echo "Appending to SOURCE_GUARDIAN_QUANTIZATIONS: '${{ fromJSON(env.SOURCE_GUARDIAN_QUANTIZATIONS) }}'"
          TEMP_ARRAY_STRING="${{ join(fromJSON(env.SOURCE_GUARDIAN_QUANTIZATIONS), env.ARRAY_SEP) }}"
          echo "TEMP_ARRAY_STRING=$TEMP_ARRAY_STRING"
          TARGET_OLLAMA_GUARDIAN_QUANTS="['${TEMP_ARRAY_STRING}${{env.ARRAY_SEP}}${{env.QUANT_F16}}']"
          echo "TARGET_OLLAMA_GUARDIAN_QUANTS=$TARGET_OLLAMA_GUARDIAN_QUANTS" >> $GITHUB_ENV

      - name: Append f16 to Ollama embedding quants
        id: ollama-append-embedding-quants
        run: |
          echo "Appending to SOURCE_EMBEDDING_QUANTIZATIONS: '${{ fromJSON(env.SOURCE_EMBEDDING_QUANTIZATIONS) }}'"
          TEMP_ARRAY_STRING="${{ join(fromJSON(env.SOURCE_EMBEDDING_QUANTIZATIONS), env.ARRAY_SEP) }}"
          echo "TEMP_ARRAY_STRING=$TEMP_ARRAY_STRING"
          TARGET_OLLAMA_EMBEDDING_QUANTS="['${TEMP_ARRAY_STRING}${{env.ARRAY_SEP}}${{env.QUANT_F16}}']"
          echo "TARGET_OLLAMA_EMBEDDING_QUANTS=$TARGET_OLLAMA_EMBEDDING_QUANTS" >> $GITHUB_ENV

      - name: Append f16 to Ollama vision quants
        id: ollama-append-vision-quants
        run: |
          echo "Appending to SOURCE_VISION_QUANTIZATIONS: '${{ fromJSON(env.SOURCE_VISION_QUANTIZATIONS) }}'"
          TEMP_ARRAY_STRING="${{ join(fromJSON(env.SOURCE_VISION_QUANTIZATIONS), env.ARRAY_SEP) }}"
          echo "TEMP_ARRAY_STRING=$TEMP_ARRAY_STRING"
          TARGET_OLLAMA_VISION_QUANTS="['${TEMP_ARRAY_STRING}${{env.ARRAY_SEP}}${{env.QUANT_F16}}']"
          echo "TARGET_OLLAMA_VISION_QUANTS=$TARGET_OLLAMA_VISION_QUANTS" >> $GITHUB_ENV

      - name: Set environment variables in GitHub output
        id: set-vars
        run: |
            echo "DEBUG: $DEBUG"
            echo "TRACE: $TRACE"
            echo "COLLECTION_CONFIG: $COLLECTION_CONFIG"
            echo "SOURCE_HF_REPO_NAME_EXT: $SOURCE_HF_REPO_NAME_EXT"
            echo "SOURCE_HF_REPO_OWNER: $SOURCE_HF_REPO_OWNER"
            echo "debug=$DEBUG" >> "$GITHUB_OUTPUT"
            echo "trace=$TRACE" >> "$GITHUB_OUTPUT"
            echo "enable_language_jobs=$ENABLE_LANGUAGE_JOBS" >> "$GITHUB_OUTPUT"
            echo "enable_vision_jobs=$ENABLE_VISION_JOBS" >> "$GITHUB_OUTPUT"
            echo "enable_guardian_jobs=$ENABLE_GUARDIAN_JOBS" >> "$GITHUB_OUTPUT"
            echo "enable_embedding_jobs=$ENABLE_EMBEDDING_JOBS" >> "$GITHUB_OUTPUT"
            echo "hf_collection_config=$COLLECTION_CONFIG" >> "$GITHUB_OUTPUT"
            echo "source_repo_name_ext=$SOURCE_HF_REPO_NAME_EXT" >> "$GITHUB_OUTPUT"
            echo "source_repo_owner=$SOURCE_HF_REPO_OWNER" >> "$GITHUB_OUTPUT"
            echo "source_instruct_repos=$SOURCE_INSTRUCT_REPOS" >> "$GITHUB_OUTPUT"
            echo "source_instruct_quantizations=$SOURCE_INSTRUCT_QUANTIZATIONS" >> "$GITHUB_OUTPUT"
            echo "source_repo_private=$SOURCE_HF_REPO_PRIVATE" >> "$GITHUB_OUTPUT"
            echo "source_vision_repos=$SOURCE_VISION_REPOS" >> "$GITHUB_OUTPUT"
            echo "source_vision_quantizations=$SOURCE_VISION_QUANTIZATIONS" >> "$GITHUB_OUTPUT"
            echo "source_guardian_repos=$SOURCE_GUARDIAN_REPOS" >> "$GITHUB_OUTPUT"
            echo "source_guardian_quantizations=$SOURCE_GUARDIAN_QUANTIZATIONS" >> "$GITHUB_OUTPUT"
            echo "source_embedding_repos=$SOURCE_EMBEDDING_REPOS" >> "$GITHUB_OUTPUT"
            echo "source_embedding_quantizations=$SOURCE_EMBEDDING_QUANTIZATIONS" >> "$GITHUB_OUTPUT"
            echo "enable_ollama_push=$ENABLE_OLLAMA_PUSH" >> "$GITHUB_OUTPUT"
            echo "target_ollama_org=$TARGET_OLLAMA_ORG" >> "$GITHUB_OUTPUT"
            echo "target_ollama_llm_quants=$TARGET_OLLAMA_LLM_QUANTS" >> "$GITHUB_OUTPUT"
            echo "target_ollama_guardian_quants=$TARGET_OLLAMA_GUARDIAN_QUANTS" >> "$GITHUB_OUTPUT"
            echo "target_ollama_embedding_quants=$TARGET_OLLAMA_EMBEDDING_QUANTS" >> "$GITHUB_OUTPUT"
            echo "target_ollama_vision_quants=$TARGET_OLLAMA_VISION_QUANTS" >> "$GITHUB_OUTPUT"

      - name: Verify updated environment variables
        id: verify-updated-env-vars
        run: env | sort

      - name: Confirm GitHub output values were set
        run: |
            echo "ollama_debug: ${{ steps.set-vars.outputs.ollama_debug }}"
            echo "debug: ${{ steps.set-vars.outputs.debug }}"
            echo "trace: ${{ steps.set-vars.outputs.trace }}"
            echo "enable_language_jobs: ${{ steps.set-vars.outputs.enable_language_jobs }}"
            echo "enable_vision_jobs: ${{ steps.set-vars.outputs.enable_vision_jobs }}"
            echo "enable_guardian_jobs: ${{ steps.set-vars.outputs.enable_guardian_jobs }}"
            echo "enable_embedding_jobs: ${{ steps.set-vars.outputs.enable_embedding_jobs }}"
            echo "hf_collection_config: '${{ steps.set-vars.outputs.hf_collection_config }}'"
            echo "source_repo_owner: '${{ steps.set-vars.outputs.source_repo_owner }}'"
            echo "source_repo_name_ext: '${{ steps.set-vars.outputs.source_repo_name_ext }}'"
            echo "source_repo_private: '${{ steps.set-vars.outputs.source_repo_private }}'"
            echo "source_instruct_repos: '${{ steps.set-vars.outputs.source_instruct_repos }}'"
            echo "source_instruct_quantizations: '${{ steps.set-vars.outputs.source_instruct_quantizations }}'"
            echo "source_vision_repos: '${{ steps.set-vars.outputs.source_vision_repos }}'"
            echo "source_vision_quantizations: '${{ steps.set-vars.outputs.source_vision_quantizations }}'"
            echo "source_guardian_repos: '${{ steps.set-vars.outputs.source_guardian_repos }}'"
            echo "source_guardian_quantizations: '${{ steps.set-vars.outputs.source_guardian_quantizations }}'"
            echo "source_embedding_repos: '${{ steps.set-vars.outputs.source_embedding_repos }}'"
            echo "source_embedding_quantizations: '${{ steps.set-vars.outputs.source_embedding_quantizations }}'"
            echo "enable_ollama_push: '${{ steps.set-vars.outputs.enable_ollama_push }}'"
            echo "target_ollama_org: '${{ steps.set-vars.outputs.target_ollama_org }}'"
            echo "target_ollama_llm_quants: '${{ steps.set-vars.outputs.target_ollama_llm_quants }}'"
            echo "target_ollama_guardian_quants: '${{ steps.set-vars.outputs.target_ollama_guardian_quants }}'"
            echo "target_ollama_embedding_quants: '${{ steps.set-vars.outputs.target_ollama_embedding_quants }}'"
            echo "target_ollama_vision_quants: '${{ steps.set-vars.outputs.target_ollama_vision_quants }}'"

      # - name: List all environment variables
      #   run: env | sort

      # - name: Dump runner context
      #   env:
      #     RUNNER_CONTEXT: ${{ toJson(runner) }}
      #   run: |
      #     uname -a
      #     echo "$RUNNER_CONTEXT"

  # ===========================================================================
  # Ollama (llm/instruct)
  # ===========================================================================
  ollama-release-llm-models:
    needs: [ environment-setup ]
    uses: ibm-granite/gguf/.github/workflows/reusable-create-push-ollama-model.yml@main
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        repo_id: ${{ fromJson(needs.environment-setup.outputs.source_instruct_repos) }}
        quantization: ${{ fromJson(needs.environment-setup.outputs.target_ollama_llm_quants) }}
    with:
      debug: ${{ needs.environment-setup.outputs.debug == 'true' }}
      hf_collection_config: ${{ needs.environment-setup.outputs.hf_collection_config }}
      enable_ollama_push: ${{ needs.environment-setup.outputs.enable_ollama_push == 'true' }}
      enable_language_jobs: ${{ needs.environment-setup.outputs.enable_language_jobs == 'true' }}
      source_repo_owner: ${{ needs.environment-setup.outputs.source_repo_owner }}
      source_repo_name_ext: ${{ needs.environment-setup.outputs.source_repo_name_ext }}
      target_ollama_org: ${{ needs.environment-setup.outputs.target_ollama_org }}
      repo_id: ${{ matrix.repo_id }}
      quantization: ${{ matrix.quantization }}
    secrets:
      hf_token: ${{ secrets.HF_TOKEN_TEST }}
      ollama_token: ${{ secrets.OLLAMA_TOKEN }}

  # ===========================================================================
  # Ollama (guardian)
  # ===========================================================================
  ollama-release-guardian-models:
    needs: [ environment-setup ]
    uses: ibm-granite/gguf/.github/workflows/reusable-create-push-ollama-model.yml@main
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        repo_id: ${{ fromJson(needs.environment-setup.outputs.source_guardian_repos) }}
        quantization: ${{ fromJson(needs.environment-setup.outputs.target_ollama_guardian_quants) }}
    with:
      debug: ${{ needs.environment-setup.outputs.debug == 'true' }}
      hf_collection_config: ${{ needs.environment-setup.outputs.hf_collection_config }}
      enable_ollama_push: ${{ needs.environment-setup.outputs.enable_ollama_push == 'true' }}
      enable_guardian_jobs: ${{ needs.environment-setup.outputs.enable_guardian_jobs == 'true' }}
      source_repo_owner: ${{ needs.environment-setup.outputs.source_repo_owner }}
      source_repo_name_ext: ${{ needs.environment-setup.outputs.source_repo_name_ext }}
      target_ollama_org: ${{ needs.environment-setup.outputs.target_ollama_org }}
      repo_id: ${{ matrix.repo_id }}
      quantization: ${{ matrix.quantization }}
    secrets:
      hf_token: ${{ secrets.HF_TOKEN_TEST }}
      ollama_token: ${{ secrets.OLLAMA_TOKEN }}

  # ===========================================================================
  # Ollama (embedding)
  # ===========================================================================
  ollama-release-embedding-models:
    needs: [ environment-setup ]
    uses: ibm-granite/gguf/.github/workflows/reusable-create-push-ollama-model.yml@main
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        repo_id: ${{ fromJson(needs.environment-setup.outputs.source_embedding_repos) }}
        quantization: ${{ fromJson(needs.environment-setup.outputs.target_ollama_embedding_quants) }}
    with:
      debug: ${{ needs.environment-setup.outputs.debug == 'true' }}
      hf_collection_config: ${{ needs.environment-setup.outputs.hf_collection_config }}
      enable_ollama_push: ${{ needs.environment-setup.outputs.enable_ollama_push == 'true' }}
      enable_embedding_jobs: ${{ needs.environment-setup.outputs.enable_embedding_jobs == 'true' }}
      source_repo_owner: ${{ needs.environment-setup.outputs.source_repo_owner }}
      source_repo_name_ext: ${{ needs.environment-setup.outputs.source_repo_name_ext }}
      target_ollama_org: ${{ needs.environment-setup.outputs.target_ollama_org }}
      repo_id: ${{ matrix.repo_id }}
      quantization: ${{ matrix.quantization }}
    secrets:
      hf_token: ${{ secrets.HF_TOKEN_TEST }}
      ollama_token: ${{ secrets.OLLAMA_TOKEN }}

  # ===========================================================================
  # Ollama (vision)
  # ===========================================================================
  ollama-release-vision-models:
    needs: [ environment-setup ]
    uses: ibm-granite/gguf/.github/workflows/reusable-create-push-ollama-model.yml@main
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        repo_id: ${{ fromJson(needs.environment-setup.outputs.source_vision_repos) }}
        quantization: ${{ fromJson(needs.environment-setup.outputs.target_ollama_vision_quants) }}
    with:
      debug: ${{ needs.environment-setup.outputs.debug == 'true' }}
      hf_collection_config: ${{ needs.environment-setup.outputs.hf_collection_config }}
      enable_ollama_push: ${{ needs.environment-setup.outputs.enable_ollama_push == 'true' }}
      enable_embedding_jobs: ${{ needs.environment-setup.outputs.enable_vision_jobs == 'true' }}
      source_repo_owner: ${{ needs.environment-setup.outputs.source_repo_owner }}
      source_repo_name_ext: ${{ needs.environment-setup.outputs.source_repo_name_ext }}
      target_ollama_org: ${{ needs.environment-setup.outputs.target_ollama_org }}
      repo_id: ${{ matrix.repo_id }}
      quantization: ${{ matrix.quantization }}
    secrets:
      hf_token: ${{ secrets.HF_TOKEN_TEST }}
      ollama_token: ${{ secrets.OLLAMA_TOKEN }}
